.\"
.\" "$Id$"
.\"
.\" ippserver man page for CUPS.
.\"
.\" Copyright 2014-2015 by Apple Inc.
.\"
.\" These coded instructions, statements, and computer programs are the
.\" property of Apple Inc. and are protected by Federal copyright
.\" law.  Distribution and use rights are outlined in the file "LICENSE.txt"
.\" which should have been included with this file.  If this file is
.\" file is missing or damaged, see the license at "http://www.cups.org/".
.\"
.TH ippserver 1 "IPPSAMPLE" "30 November 2015" "Apple Inc."
.SH NAME
ippserver \- a simple ipp server
.SH SYNOPSIS
.B ippserver
[
.B \-d
.I spool-directory
] [
.B \-h
] [
.B \-k
] [
.B \-n
.I hostname
] [
.B \-p
.I port
] [
.B \-u
.I username:password
] [
.B \-v[vvv]
]
.I service-name
.SH DESCRIPTION
.B ippserver
is a simple Internet Printing Protocol (IPP) infrastructure server conforming to the IPP Shared Infrastructure Extensions (INFRA) specification. It can be used as a very basic infrastructure server between standard IPP clients and IPP proxies conforming to the INFRA specification.
.SH OPTIONS
The following options are recognized by
.B ippserver:
.TP 5
\fB\-d \fIspool-directory\fR
Specifies the directory that will hold the print files.
The default is a directory under the user's current temporary directory.
.TP 5
.B \-h
Shows program help.
.TP 5
.B \-k
Keeps the print documents in the spool directory rather than deleting them.
.TP 5
\fB\-n \fIhostname\fR
Specifies the hostname that is reported by the server.
The default is the name returned by the
.BR hostname (1)
command.
.TP 5
\fB\-p \fIport\fR
Specifies the port number to listen on.
The default is a user-specific number from 8000 to 8999.
.TP 5
\fB\-u \fIusername:password\fR
Specifies the username and password for the IPP proxy.
The default is "test:test123".
.TP 5
.B \-v[vvv]
Be (very) verbose when logging activity to the standard output.
.SH EXIT STATUS
The
.B ippserver
program returns 1 if it is unable to process the command-line arguments.
Otherwise
.B ippserver
will run continuously until terminated.
.SH CONFORMING TO
The
.B ippserver
program is unique to CUPS and conforms to the IPP Shared Infrastructure Extensions (INFRA) specification as an Infrastructure Printer.
.SH EXAMPLES
Run
.B ippserver
with a service name of My Cool Printer:
.nf

    ippserver "My Cool Printer"
.fi
.LP
Specify a proxy username of "foo" and password of "bar":
.nf

    ippserver \-u foo:bar "My Cool Printer"
.fi
.SH SEE ALSO
PWG Internet Printing Protocol Workgroup (http://www.pwg.org/ipp)
.SH COPYRIGHT
Copyright \[co] 2007-2014 by Apple Inc.
.\"
.\" End of "$Id$".
.\"
