#!/bin/sh
#
# makesrcdist - make a source distribution of the IPP sample code.
#

if test $# != 1; then
	echo "Usage: ./makesrcdist version"
	exit 1
fi

version=$1

echo Creating tag for release...
git tag -m "Tag $version" v$version
git push origin v$version

echo Archiving source...
rm -rf .tmp/ippsample-$version
mkdir -p .tmp/ippsample-$version
git archive HEAD | (cd .tmp/ippsample-$version; tar xf -)

for sm in libcups pdfio; do
	(cd $sm; git archive --prefix=$sm/ HEAD) | (cd .tmp/ippsample-$version; tar xf -)
done

echo Creating ippsample-$version.tar.gz...
(cd .tmp; tar czf ../ippsample-$version.tar.gz ippsample-$version)
gpg --detach-sign ippsample-$version.tar.gz

echo Creating ippsample-$version.zip...
rm -f ippsample-$version.zip
(cd .tmp; zip -rq9 ../ippsample-$version.zip ippsample-$version)
gpg --detach-sign ippsample-$version.zip

echo Cleaning up...
rm -rf .tmp
