name: ipp
version: 1.0b1
summary: IPP Sample Implementation
description: |
  The ippsample project provides sample implementations of an IPP Client, Proxy,
  Server, and other tools. It is based on the CUPS source code and is maintained
  by the PWG IPP workgroup.

grade: stable
confinement: strict
icon: server/printer.png

apps:
    server:
        command: sbin/server
        plugs: [avahi-observe, home, network, network-bind]
    eveprinter:
        command: bin/eveprinter
        plugs: [avahi-observe, home, network, network-bind]
    find:
        command: bin/find
        plugs: [avahi-observe, home, network]
    proxy:
        command: sbin/proxy
        plugs: [avahi-observe, home, network]
    tool:
        command: bin/tool
        plugs: [home, network]

parts:
    mupdf:
        plugin: make
        make-install-var: prefix
        make-parameters: [HAVE_X11=no, HAVE_GLFW=no, HAVE_GLUT=no, USE_SYSTEM_LIBS=yes]
        source: https://mupdf.com/downloads/archive/mupdf-1.12.0-source.tar.gz
        prime:
            - -bin/mu*
            - -include/mu*
            - -lib/libmu*
            - -share/doc/mupdf
            - -share/man/man1/mu*
        build-packages: [libfreetype6-dev, libharfbuzz-dev, libjbig2dec0-dev, libjpeg-dev, liblcms2-dev, libopenjp2-7-dev, libpng-dev, zlib1g-dev]

    main:
        after: [mupdf]
        plugin: autotools
        configflags: [--with-name-prefix=]
        source: .
        build-packages: [cura-engine, libavahi-client-dev, libfreetype6-dev, libgnutls28-dev, libharfbuzz-dev, libjbig2dec0-dev, libjpeg-dev, liblcms2-dev, libopenjp2-7-dev, libpng-dev, zlib1g-dev]
        stage-packages: [libavahi-client3, libjpeg-turbo8, libopenjp2-7]

